# Sample config for run_iwe_pipeline.py
limit: 100
monitor: false
job_name: iwe_local

executor:
  tasks: 1
  workers: 1

reader:
  input_dir: "???"
  backend: local # local | azure
  pdf_to_ppm: true
  target_longest_image_dim: 2048
  yield_pages_as_documents: false
  glob_pattern: "**/*.pdf"
  recursive: true
  limit: ${limit}

  azure:
    container_path: az://mycontainer

ocr:
  server_url: "???"
  model_name: "???"
  server_api_key: null
  temperature: 0.0
  max_concurrent: 8
  max_tokens: 2048
  checkpoints_local_dir: null

output:
  output_dir: "???"
  backend: local # local | azure
  output_filename: rank_\${rank}_chunk_\${chunk_index}_output.jsonl

  azure:
    container_path: az://mycontainer
