# Sample config for run_iwe_pipeline.py
hydra:
  run:
    dir: outputs/${job_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

limit: -1
monitor: false
job_name: iwe_local

executor:
  tasks: 1
  workers: 1

reader:
  input_dir: "???"
  backend: local # local | azure
  pdf_to_ppm: true
  target_longest_image_dim: 2048
  yield_pages_as_documents: false
  glob_pattern: "**/*.pdf"
  recursive: true
  limit: ${limit}

  azure:
    container_path: az://mycontainer

ocr:
  server_url: "???"
  model_name: "???"
  server_api_key: null
  temperature: 0.0
  max_concurrent: 8
  max_tokens: 2048
  checkpoints_local_dir: null

classifiers:
  ocr_classifier_model_path: "???"

output:
  output_dir: "???"
  backend: local # local | azure
  output_filename: rank_\${rank}_chunk_\${chunk_index}_output.jsonl

  azure:
    container_path: az://mycontainer

azure:
  timeout: 3_600
  read_timeout: 3_600
  connection_timeout: 3_600
  socket_timeout: 3_600
  blocksize: 4_194_304